# Generated by Django 5.2.12 on 2026-08-30 16:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_registrationrequest_remove_place_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_limit', models.DecimalField(decimal_places=2, help_text='Limite máximo de gastos estipulado para a categoria no mês.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('month', models.IntegerField(help_text='Mês de vigência da meta (1 a 12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(help_text='Ano de vigência da meta.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-year', '-month', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('type', models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], default='EXPENSE', max_length=10)),
                ('method', models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito'), ('CASH', 'Dinheiro'), ('PIX', 'Pix'), ('BOLETO', 'Boleto')], default='DEBIT', max_length=15)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Mensal'), ('WEEKLY', 'Semanal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=10)),
                ('day_of_month', models.IntegerField(default=1, help_text='Dia do mês programado para o vencimento/lançamento.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('is_active', models.BooleanField(default=True)),
                ('last_processed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recurring Transaction',
                'verbose_name_plural': 'Recurring Transactions',
                'ordering': ['day_of_month', 'description'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'name'], name='app_core_ac_user_id_2104e6_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='app_core_ca_user_id_8e2161_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name'], name='app_core_ca_user_id_dd0cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationrequest',
            index=models.Index(fields=['status', '-created_at'], name='registratio_status_1dd219_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='app_core_tr_user_id_883c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='app_core_tr_account_6a3301_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['installment_id_group'], name='app_core_tr_install_0df71d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='app_core_tr_user_id_1c0bc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='app_core.category'),
        ),
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='app_core.account'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_core.category'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'year', 'month'], name='app_core_bu_user_id_3e56fb_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'category'], name='app_core_bu_user_id_f77e13_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'month', 'year'), name='unique_budget_per_user_category_month_year'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active'], name='app_core_re_user_id_16a231_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'day_of_month'], name='app_core_re_user_id_52dba5_idx'),
        ),
    ]
