# Generated by Django 5.2.12 on 2026-08-30 18:30

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_budget_recurringtransaction_account_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACCEPTED', 'Aceito'), ('REJECTED', 'Recusado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_transfers', to=settings.AUTH_USER_MODEL)),
                ('receiver_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_peer_transfers', to='app_core.account')),
                ('receiver_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_peer_transfer', to='app_core.transaction')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_peer_transfers', to=settings.AUTH_USER_MODEL)),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_peer_transfers', to='app_core.account')),
                ('sender_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_peer_transfer', to='app_core.transaction')),
            ],
            options={
                'db_table': 'peer_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='peer_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='app_core.peertransfer'),
        ),
        migrations.AddIndex(
            model_name='peertransfer',
            index=models.Index(fields=['sender', 'status', '-created_at'], name='peer_transf_sender__415890_idx'),
        ),
        migrations.AddIndex(
            model_name='peertransfer',
            index=models.Index(fields=['receiver', 'status', '-created_at'], name='peer_transf_receive_dc1c16_idx'),
        ),
    ]
