# Generated by Django 5.2.12 on 2026-09-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_peertransfer_notification_peer_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
