# Generated by Django 5.2.12 on 2026-09-02 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_transaction_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='month_of_year',
            field=models.IntegerField(blank=True, help_text='Mês do ano para cobrança anual (1-12).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
