# Generated by Django 5.2.12 on 2026-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_recurringtransaction_month_of_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('BANK', 'Banco'), ('WALLET', 'Carteira'), ('INVESTMENT', 'Investimento'), ('CREDIT', 'Cartão de Crédito'), ('OTHER', 'Outros')], max_length=15),
        ),
    ]
